// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/w/hallb-scifs17exp/clas12/bclary/CLAS12/phi_analysis/pid/./filter_clas12_v4.cxx";

#endif
