import org.jlab.analysis.plotting.H1FCollection2D;
import org.jlab.analysis.plotting.H1FCollection3D;
import org.jlab.analysis.plotting.TCanvasP;
import org.jlab.analysis.plotting.TCanvasPTabbed;
import org.jlab.analysis.math.ClasMath;
import org.jlab.clas.physics.Vector3;
import org.jlab.clas.physics.LorentzVector;
import org.jlab.groot.data.H1F;
import org.jlab.groot.data.H2F;
import org.jlab.io.base.DataBank;
import org.jlab.io.base.DataEvent;
import org.jlab.io.hipo.HipoDataSource;
import org.jlab.groot.graphics.EmbeddedCanvas;
import org.jlab.groot.fitter.ParallelSliceFitter;
import org.jlab.groot.data.GraphErrors;
import org.jlab.groot.data.TDirectory;

System.setProperty("java.awt.headless", "true");

String fieldconf1 = "tp75_s70";
TDirectory dir1 = new TDirectory();
dir1.readFile(String.format("prod_phi_%s/res_hists.hipo",fieldconf1));
TDirectory dir_res1 = new TDirectory();
dir_res1.readFile(String.format("prod_phi_%s/res_graphs.hipo",fieldconf1));
String fieldconf2 = "tm75_s70";
TDirectory dir2 = new TDirectory();
dir2.readFile(String.format("prod_phi_%s/res_hists.hipo",fieldconf2));
TDirectory dir_res2 = new TDirectory();
dir_res2.readFile(String.format("prod_phi_%s/res_graphs.hipo",fieldconf2));
String fieldconf3 = "tp1_s1";
TDirectory dir3 = new TDirectory();
dir3.readFile(String.format("prod_phi_%s/res_hists.hipo",fieldconf3));
TDirectory dir_res3 = new TDirectory();
dir_res3.readFile(String.format("prod_phi_%s/res_graphs.hipo",fieldconf3));
String fieldconf4 = "tm1_s1";
TDirectory dir4 = new TDirectory();
dir4.readFile(String.format("prod_phi_%s/res_hists.hipo",fieldconf4));
TDirectory dir_res4 = new TDirectory();
dir_res4.readFile(String.format("prod_phi_%s/res_graphs.hipo",fieldconf4));
String fieldconf5 = "release_4a82_validation";
TDirectory dir5 = new TDirectory();
dir5.readFile(String.format("%s/res_hists.hipo",fieldconf5));
TDirectory dir_res5 = new TDirectory();
dir_res5.readFile(String.format("%s/res_graphs.hipo",fieldconf5));

H1F A2_Phi_1  = (H1F)dir1.getObject("/kine/A2_Phi");A2_Phi_1.setLineColor(2);A2_Phi_1.setLineWidth(3);
H1F A2_t_1    = (H1F)dir1.getObject("/kine/A2_t");A2_t_1.setLineColor(2);A2_t_1.setLineWidth(3);
H1F A2_xB_1   = (H1F)dir1.getObject("/kine/A2_xB");A2_xB_1.setLineColor(2);A2_xB_1.setLineWidth(3);
H1F A2_Q2_1   = (H1F)dir1.getObject("/kine/A2_Q2");A2_Q2_1.setLineColor(2);A2_Q2_1.setLineWidth(3);
H1F A2_Phi_2  = (H1F)dir2.getObject("/kine/A2_Phi");A2_Phi_2.setLineColor(3);A2_Phi_2.setLineWidth(3);
H1F A2_t_2    = (H1F)dir2.getObject("/kine/A2_t");A2_t_2.setLineColor(3);A2_t_2.setLineWidth(3);
H1F A2_xB_2   = (H1F)dir2.getObject("/kine/A2_xB");A2_xB_2.setLineColor(3);A2_xB_2.setLineWidth(3);
H1F A2_Q2_2   = (H1F)dir2.getObject("/kine/A2_Q2");A2_Q2_2.setLineColor(3);A2_Q2_2.setLineWidth(3);
H1F A2_Phi_3  = (H1F)dir3.getObject("/kine/A2_Phi");A2_Phi_3.setLineColor(4);A2_Phi_3.setLineWidth(3);
H1F A2_t_3    = (H1F)dir3.getObject("/kine/A2_t");A2_t_3.setLineColor(4);A2_t_3.setLineWidth(3);
H1F A2_xB_3   = (H1F)dir3.getObject("/kine/A2_xB");A2_xB_3.setLineColor(4);A2_xB_3.setLineWidth(3);
H1F A2_Q2_3   = (H1F)dir3.getObject("/kine/A2_Q2");A2_Q2_3.setLineColor(4);A2_Q2_3.setLineWidth(3);
H1F A2_Phi_4  = (H1F)dir4.getObject("/kine/A2_Phi");A2_Phi_4.setLineColor(5);A2_Phi_4.setLineWidth(3);
H1F A2_t_4    = (H1F)dir4.getObject("/kine/A2_t");A2_t_4.setLineColor(5);A2_t_4.setLineWidth(3);
H1F A2_xB_4   = (H1F)dir4.getObject("/kine/A2_xB");A2_xB_4.setLineColor(5);A2_xB_4.setLineWidth(3);
H1F A2_Q2_4   = (H1F)dir4.getObject("/kine/A2_Q2");A2_Q2_4.setLineColor(5);A2_Q2_4.setLineWidth(3);
H1F A2_Phi_5  = (H1F)dir5.getObject("/kine/A2_Phi");A2_Phi_4.setLineWidth(3);//A2_Phi_4.setLineColor(5);
H1F A2_t_5    = (H1F)dir5.getObject("/kine/A2_t");A2_t_4.setLineWidth(3);//A2_t_4.setLineColor(5);
H1F A2_xB_5   = (H1F)dir5.getObject("/kine/A2_xB");A2_xB_4.setLineWidth(3);//A2_xB_4.setLineColor(5);
H1F A2_Q2_5   = (H1F)dir5.getObject("/kine/A2_Q2");A2_Q2_4.setLineWidth(3);//A2_Q2_4.setLineColor(5);

GraphErrors gr_s_fit_el_p_p_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_el_p_p");gr_s_fit_el_p_p_1.setMarkerColor(2);
GraphErrors gr_s_fit_el_t_p_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_el_t_p");gr_s_fit_el_t_p_1.setMarkerColor(2);
GraphErrors gr_s_fit_el_f_p_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_el_f_p");gr_s_fit_el_f_p_1.setMarkerColor(2);
GraphErrors gr_s_fit_el_v_p_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_el_v_p");gr_s_fit_el_v_p_1.setMarkerColor(2);
GraphErrors gr_s_fit_el_p_t_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_el_p_t");gr_s_fit_el_p_t_1.setMarkerColor(2);
GraphErrors gr_s_fit_el_t_t_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_el_t_t");gr_s_fit_el_t_t_1.setMarkerColor(2);
GraphErrors gr_s_fit_el_f_t_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_el_f_t");gr_s_fit_el_f_t_1.setMarkerColor(2);
GraphErrors gr_s_fit_el_v_t_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_el_v_t");gr_s_fit_el_v_t_1.setMarkerColor(2);
GraphErrors gr_s_fit_pr_p_p_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_pr_p_p");gr_s_fit_pr_p_p_1.setMarkerColor(2);
GraphErrors gr_s_fit_pr_t_p_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_pr_t_p");gr_s_fit_pr_t_p_1.setMarkerColor(2);
GraphErrors gr_s_fit_pr_f_p_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_pr_f_p");gr_s_fit_pr_f_p_1.setMarkerColor(2);
GraphErrors gr_s_fit_pr_v_p_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_pr_v_p");gr_s_fit_pr_v_p_1.setMarkerColor(2);
GraphErrors gr_s_fit_pr_p_t_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_pr_p_t");gr_s_fit_pr_p_t_1.setMarkerColor(2);
GraphErrors gr_s_fit_pr_t_t_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_pr_t_t");gr_s_fit_pr_t_t_1.setMarkerColor(2);
GraphErrors gr_s_fit_pr_f_t_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_pr_f_t");gr_s_fit_pr_f_t_1.setMarkerColor(2);
GraphErrors gr_s_fit_pr_v_t_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_pr_v_t");gr_s_fit_pr_v_t_1.setMarkerColor(2);
GraphErrors gr_s_fit_kp_p_p_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_kp_p_p");gr_s_fit_kp_p_p_1.setMarkerColor(2);
GraphErrors gr_s_fit_kp_t_p_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_kp_t_p");gr_s_fit_kp_t_p_1.setMarkerColor(2);
GraphErrors gr_s_fit_kp_f_p_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_kp_f_p");gr_s_fit_kp_f_p_1.setMarkerColor(2);
GraphErrors gr_s_fit_kp_v_p_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_kp_v_p");gr_s_fit_kp_v_p_1.setMarkerColor(2);
GraphErrors gr_s_fit_kp_p_t_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_kp_p_t");gr_s_fit_kp_p_t_1.setMarkerColor(2);
GraphErrors gr_s_fit_kp_t_t_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_kp_t_t");gr_s_fit_kp_t_t_1.setMarkerColor(2);
GraphErrors gr_s_fit_kp_f_t_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_kp_f_t");gr_s_fit_kp_f_t_1.setMarkerColor(2);
GraphErrors gr_s_fit_kp_v_t_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_kp_v_t");gr_s_fit_kp_v_t_1.setMarkerColor(2);
GraphErrors gr_s_fit_km_p_p_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_km_p_p");gr_s_fit_km_p_p_1.setMarkerColor(2);
GraphErrors gr_s_fit_km_t_p_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_km_t_p");gr_s_fit_km_t_p_1.setMarkerColor(2);
GraphErrors gr_s_fit_km_f_p_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_km_f_p");gr_s_fit_km_f_p_1.setMarkerColor(2);
GraphErrors gr_s_fit_km_v_p_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_km_v_p");gr_s_fit_km_v_p_1.setMarkerColor(2);
GraphErrors gr_s_fit_km_p_t_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_km_p_t");gr_s_fit_km_p_t_1.setMarkerColor(2);
GraphErrors gr_s_fit_km_t_t_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_km_t_t");gr_s_fit_km_t_t_1.setMarkerColor(2);
GraphErrors gr_s_fit_km_f_t_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_km_f_t");gr_s_fit_km_f_t_1.setMarkerColor(2);
GraphErrors gr_s_fit_km_v_t_1 = (GraphErrors)dir_res1.getObject("/res/gr_s_fit_km_v_t");gr_s_fit_km_v_t_1.setMarkerColor(2);

GraphErrors gr_s_fit_el_p_p_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_el_p_p");gr_s_fit_el_p_p_2.setMarkerColor(3);
GraphErrors gr_s_fit_el_t_p_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_el_t_p");gr_s_fit_el_t_p_2.setMarkerColor(3);
GraphErrors gr_s_fit_el_f_p_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_el_f_p");gr_s_fit_el_f_p_2.setMarkerColor(3);
GraphErrors gr_s_fit_el_v_p_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_el_v_p");gr_s_fit_el_v_p_2.setMarkerColor(3);
GraphErrors gr_s_fit_el_p_t_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_el_p_t");gr_s_fit_el_p_t_2.setMarkerColor(3);
GraphErrors gr_s_fit_el_t_t_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_el_t_t");gr_s_fit_el_t_t_2.setMarkerColor(3);
GraphErrors gr_s_fit_el_f_t_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_el_f_t");gr_s_fit_el_f_t_2.setMarkerColor(3);
GraphErrors gr_s_fit_el_v_t_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_el_v_t");gr_s_fit_el_v_t_2.setMarkerColor(3);
GraphErrors gr_s_fit_pr_p_p_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_pr_p_p");gr_s_fit_pr_p_p_2.setMarkerColor(3);
GraphErrors gr_s_fit_pr_t_p_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_pr_t_p");gr_s_fit_pr_t_p_2.setMarkerColor(3);
GraphErrors gr_s_fit_pr_f_p_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_pr_f_p");gr_s_fit_pr_f_p_2.setMarkerColor(3);
GraphErrors gr_s_fit_pr_v_p_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_pr_v_p");gr_s_fit_pr_v_p_2.setMarkerColor(3);
GraphErrors gr_s_fit_pr_p_t_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_pr_p_t");gr_s_fit_pr_p_t_2.setMarkerColor(3);
GraphErrors gr_s_fit_pr_t_t_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_pr_t_t");gr_s_fit_pr_t_t_2.setMarkerColor(3);
GraphErrors gr_s_fit_pr_f_t_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_pr_f_t");gr_s_fit_pr_f_t_2.setMarkerColor(3);
GraphErrors gr_s_fit_pr_v_t_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_pr_v_t");gr_s_fit_pr_v_t_2.setMarkerColor(3);
GraphErrors gr_s_fit_kp_p_p_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_kp_p_p");gr_s_fit_kp_p_p_2.setMarkerColor(3);
GraphErrors gr_s_fit_kp_t_p_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_kp_t_p");gr_s_fit_kp_t_p_2.setMarkerColor(3);
GraphErrors gr_s_fit_kp_f_p_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_kp_f_p");gr_s_fit_kp_f_p_2.setMarkerColor(3);
GraphErrors gr_s_fit_kp_v_p_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_kp_v_p");gr_s_fit_kp_v_p_2.setMarkerColor(3);
GraphErrors gr_s_fit_kp_p_t_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_kp_p_t");gr_s_fit_kp_p_t_2.setMarkerColor(3);
GraphErrors gr_s_fit_kp_t_t_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_kp_t_t");gr_s_fit_kp_t_t_2.setMarkerColor(3);
GraphErrors gr_s_fit_kp_f_t_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_kp_f_t");gr_s_fit_kp_f_t_2.setMarkerColor(3);
GraphErrors gr_s_fit_kp_v_t_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_kp_v_t");gr_s_fit_kp_v_t_2.setMarkerColor(3);
GraphErrors gr_s_fit_km_p_p_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_km_p_p");gr_s_fit_km_p_p_2.setMarkerColor(3);
GraphErrors gr_s_fit_km_t_p_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_km_t_p");gr_s_fit_km_t_p_2.setMarkerColor(3);
GraphErrors gr_s_fit_km_f_p_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_km_f_p");gr_s_fit_km_f_p_2.setMarkerColor(3);
GraphErrors gr_s_fit_km_v_p_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_km_v_p");gr_s_fit_km_v_p_2.setMarkerColor(3);
GraphErrors gr_s_fit_km_p_t_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_km_p_t");gr_s_fit_km_p_t_2.setMarkerColor(3);
GraphErrors gr_s_fit_km_t_t_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_km_t_t");gr_s_fit_km_t_t_2.setMarkerColor(3);
GraphErrors gr_s_fit_km_f_t_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_km_f_t");gr_s_fit_km_f_t_2.setMarkerColor(3);
GraphErrors gr_s_fit_km_v_t_2 = (GraphErrors)dir_res2.getObject("/res/gr_s_fit_km_v_t");gr_s_fit_km_v_t_2.setMarkerColor(3);

GraphErrors gr_s_fit_el_p_p_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_el_p_p");gr_s_fit_el_p_p_3.setMarkerColor(4);
GraphErrors gr_s_fit_el_t_p_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_el_t_p");gr_s_fit_el_t_p_3.setMarkerColor(4);
GraphErrors gr_s_fit_el_f_p_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_el_f_p");gr_s_fit_el_f_p_3.setMarkerColor(4);
GraphErrors gr_s_fit_el_v_p_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_el_v_p");gr_s_fit_el_v_p_3.setMarkerColor(4);
GraphErrors gr_s_fit_el_p_t_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_el_p_t");gr_s_fit_el_p_t_3.setMarkerColor(4);
GraphErrors gr_s_fit_el_t_t_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_el_t_t");gr_s_fit_el_t_t_3.setMarkerColor(4);
GraphErrors gr_s_fit_el_f_t_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_el_f_t");gr_s_fit_el_f_t_3.setMarkerColor(4);
GraphErrors gr_s_fit_el_v_t_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_el_v_t");gr_s_fit_el_v_t_3.setMarkerColor(4);
GraphErrors gr_s_fit_pr_p_p_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_pr_p_p");gr_s_fit_pr_p_p_3.setMarkerColor(4);
GraphErrors gr_s_fit_pr_t_p_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_pr_t_p");gr_s_fit_pr_t_p_3.setMarkerColor(4);
GraphErrors gr_s_fit_pr_f_p_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_pr_f_p");gr_s_fit_pr_f_p_3.setMarkerColor(4);
GraphErrors gr_s_fit_pr_v_p_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_pr_v_p");gr_s_fit_pr_v_p_3.setMarkerColor(4);
GraphErrors gr_s_fit_pr_p_t_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_pr_p_t");gr_s_fit_pr_p_t_3.setMarkerColor(4);
GraphErrors gr_s_fit_pr_t_t_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_pr_t_t");gr_s_fit_pr_t_t_3.setMarkerColor(4);
GraphErrors gr_s_fit_pr_f_t_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_pr_f_t");gr_s_fit_pr_f_t_3.setMarkerColor(4);
GraphErrors gr_s_fit_pr_v_t_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_pr_v_t");gr_s_fit_pr_v_t_3.setMarkerColor(4);
GraphErrors gr_s_fit_kp_p_p_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_kp_p_p");gr_s_fit_kp_p_p_3.setMarkerColor(4);
GraphErrors gr_s_fit_kp_t_p_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_kp_t_p");gr_s_fit_kp_t_p_3.setMarkerColor(4);
GraphErrors gr_s_fit_kp_f_p_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_kp_f_p");gr_s_fit_kp_f_p_3.setMarkerColor(4);
GraphErrors gr_s_fit_kp_v_p_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_kp_v_p");gr_s_fit_kp_v_p_3.setMarkerColor(4);
GraphErrors gr_s_fit_kp_p_t_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_kp_p_t");gr_s_fit_kp_p_t_3.setMarkerColor(4);
GraphErrors gr_s_fit_kp_t_t_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_kp_t_t");gr_s_fit_kp_t_t_3.setMarkerColor(4);
GraphErrors gr_s_fit_kp_f_t_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_kp_f_t");gr_s_fit_kp_f_t_3.setMarkerColor(4);
GraphErrors gr_s_fit_kp_v_t_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_kp_v_t");gr_s_fit_kp_v_t_3.setMarkerColor(4);
GraphErrors gr_s_fit_km_p_p_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_km_p_p");gr_s_fit_km_p_p_3.setMarkerColor(4);
GraphErrors gr_s_fit_km_t_p_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_km_t_p");gr_s_fit_km_t_p_3.setMarkerColor(4);
GraphErrors gr_s_fit_km_f_p_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_km_f_p");gr_s_fit_km_f_p_3.setMarkerColor(4);
GraphErrors gr_s_fit_km_v_p_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_km_v_p");gr_s_fit_km_v_p_3.setMarkerColor(4);
GraphErrors gr_s_fit_km_p_t_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_km_p_t");gr_s_fit_km_p_t_3.setMarkerColor(4);
GraphErrors gr_s_fit_km_t_t_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_km_t_t");gr_s_fit_km_t_t_3.setMarkerColor(4);
GraphErrors gr_s_fit_km_f_t_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_km_f_t");gr_s_fit_km_f_t_3.setMarkerColor(4);
GraphErrors gr_s_fit_km_v_t_3 = (GraphErrors)dir_res3.getObject("/res/gr_s_fit_km_v_t");gr_s_fit_km_v_t_3.setMarkerColor(4);

GraphErrors gr_s_fit_el_p_p_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_el_p_p");gr_s_fit_el_p_p_4.setMarkerColor(5);
GraphErrors gr_s_fit_el_t_p_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_el_t_p");gr_s_fit_el_t_p_4.setMarkerColor(5);
GraphErrors gr_s_fit_el_f_p_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_el_f_p");gr_s_fit_el_f_p_4.setMarkerColor(5);
GraphErrors gr_s_fit_el_v_p_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_el_v_p");gr_s_fit_el_v_p_4.setMarkerColor(5);
GraphErrors gr_s_fit_el_p_t_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_el_p_t");gr_s_fit_el_p_t_4.setMarkerColor(5);
GraphErrors gr_s_fit_el_t_t_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_el_t_t");gr_s_fit_el_t_t_4.setMarkerColor(5);
GraphErrors gr_s_fit_el_f_t_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_el_f_t");gr_s_fit_el_f_t_4.setMarkerColor(5);
GraphErrors gr_s_fit_el_v_t_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_el_v_t");gr_s_fit_el_v_t_4.setMarkerColor(5);
GraphErrors gr_s_fit_pr_p_p_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_pr_p_p");gr_s_fit_pr_p_p_4.setMarkerColor(5);
GraphErrors gr_s_fit_pr_t_p_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_pr_t_p");gr_s_fit_pr_t_p_4.setMarkerColor(5);
GraphErrors gr_s_fit_pr_f_p_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_pr_f_p");gr_s_fit_pr_f_p_4.setMarkerColor(5);
GraphErrors gr_s_fit_pr_v_p_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_pr_v_p");gr_s_fit_pr_v_p_4.setMarkerColor(5);
GraphErrors gr_s_fit_pr_p_t_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_pr_p_t");gr_s_fit_pr_p_t_4.setMarkerColor(5);
GraphErrors gr_s_fit_pr_t_t_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_pr_t_t");gr_s_fit_pr_t_t_4.setMarkerColor(5);
GraphErrors gr_s_fit_pr_f_t_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_pr_f_t");gr_s_fit_pr_f_t_4.setMarkerColor(5);
GraphErrors gr_s_fit_pr_v_t_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_pr_v_t");gr_s_fit_pr_v_t_4.setMarkerColor(5);
GraphErrors gr_s_fit_kp_p_p_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_kp_p_p");gr_s_fit_kp_p_p_4.setMarkerColor(5);
GraphErrors gr_s_fit_kp_t_p_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_kp_t_p");gr_s_fit_kp_t_p_4.setMarkerColor(5);
GraphErrors gr_s_fit_kp_f_p_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_kp_f_p");gr_s_fit_kp_f_p_4.setMarkerColor(5);
GraphErrors gr_s_fit_kp_v_p_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_kp_v_p");gr_s_fit_kp_v_p_4.setMarkerColor(5);
GraphErrors gr_s_fit_kp_p_t_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_kp_p_t");gr_s_fit_kp_p_t_4.setMarkerColor(5);
GraphErrors gr_s_fit_kp_t_t_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_kp_t_t");gr_s_fit_kp_t_t_4.setMarkerColor(5);
GraphErrors gr_s_fit_kp_f_t_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_kp_f_t");gr_s_fit_kp_f_t_4.setMarkerColor(5);
GraphErrors gr_s_fit_kp_v_t_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_kp_v_t");gr_s_fit_kp_v_t_4.setMarkerColor(5);
GraphErrors gr_s_fit_km_p_p_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_km_p_p");gr_s_fit_km_p_p_4.setMarkerColor(5);
GraphErrors gr_s_fit_km_t_p_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_km_t_p");gr_s_fit_km_t_p_4.setMarkerColor(5);
GraphErrors gr_s_fit_km_f_p_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_km_f_p");gr_s_fit_km_f_p_4.setMarkerColor(5);
GraphErrors gr_s_fit_km_v_p_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_km_v_p");gr_s_fit_km_v_p_4.setMarkerColor(5);
GraphErrors gr_s_fit_km_p_t_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_km_p_t");gr_s_fit_km_p_t_4.setMarkerColor(5);
GraphErrors gr_s_fit_km_t_t_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_km_t_t");gr_s_fit_km_t_t_4.setMarkerColor(5);
GraphErrors gr_s_fit_km_f_t_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_km_f_t");gr_s_fit_km_f_t_4.setMarkerColor(5);
GraphErrors gr_s_fit_km_v_t_4 = (GraphErrors)dir_res4.getObject("/res/gr_s_fit_km_v_t");gr_s_fit_km_v_t_4.setMarkerColor(5);

GraphErrors gr_s_fit_el_p_p_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_el_p_p");gr_s_fit_el_p_p_5.setMarkerSize(4);
GraphErrors gr_s_fit_el_t_p_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_el_t_p");gr_s_fit_el_t_p_5.setMarkerSize(4);
GraphErrors gr_s_fit_el_f_p_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_el_f_p");gr_s_fit_el_f_p_5.setMarkerSize(4);
GraphErrors gr_s_fit_el_v_p_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_el_v_p");gr_s_fit_el_v_p_5.setMarkerSize(4);
GraphErrors gr_s_fit_el_p_t_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_el_p_t");gr_s_fit_el_p_t_5.setMarkerSize(4);
GraphErrors gr_s_fit_el_t_t_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_el_t_t");gr_s_fit_el_t_t_5.setMarkerSize(4);
GraphErrors gr_s_fit_el_f_t_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_el_f_t");gr_s_fit_el_f_t_5.setMarkerSize(4);
GraphErrors gr_s_fit_el_v_t_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_el_v_t");gr_s_fit_el_v_t_5.setMarkerSize(4);
GraphErrors gr_s_fit_pr_p_p_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_pr_p_p");gr_s_fit_pr_p_p_5.setMarkerSize(4);
GraphErrors gr_s_fit_pr_t_p_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_pr_t_p");gr_s_fit_pr_t_p_5.setMarkerSize(4);
GraphErrors gr_s_fit_pr_f_p_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_pr_f_p");gr_s_fit_pr_f_p_5.setMarkerSize(4);
GraphErrors gr_s_fit_pr_v_p_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_pr_v_p");gr_s_fit_pr_v_p_5.setMarkerSize(4);
GraphErrors gr_s_fit_pr_p_t_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_pr_p_t");gr_s_fit_pr_p_t_5.setMarkerSize(4);
GraphErrors gr_s_fit_pr_t_t_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_pr_t_t");gr_s_fit_pr_t_t_5.setMarkerSize(4);
GraphErrors gr_s_fit_pr_f_t_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_pr_f_t");gr_s_fit_pr_f_t_5.setMarkerSize(4);
GraphErrors gr_s_fit_pr_v_t_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_pr_v_t");gr_s_fit_pr_v_t_5.setMarkerSize(4);
GraphErrors gr_s_fit_kp_p_p_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_kp_p_p");gr_s_fit_kp_p_p_5.setMarkerSize(4);
GraphErrors gr_s_fit_kp_t_p_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_kp_t_p");gr_s_fit_kp_t_p_5.setMarkerSize(4);
GraphErrors gr_s_fit_kp_f_p_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_kp_f_p");gr_s_fit_kp_f_p_5.setMarkerSize(4);
GraphErrors gr_s_fit_kp_v_p_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_kp_v_p");gr_s_fit_kp_v_p_5.setMarkerSize(4);
GraphErrors gr_s_fit_kp_p_t_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_kp_p_t");gr_s_fit_kp_p_t_5.setMarkerSize(4);
GraphErrors gr_s_fit_kp_t_t_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_kp_t_t");gr_s_fit_kp_t_t_5.setMarkerSize(4);
GraphErrors gr_s_fit_kp_f_t_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_kp_f_t");gr_s_fit_kp_f_t_5.setMarkerSize(4);
GraphErrors gr_s_fit_kp_v_t_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_kp_v_t");gr_s_fit_kp_v_t_5.setMarkerSize(4);
GraphErrors gr_s_fit_km_p_p_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_km_p_p");gr_s_fit_km_p_p_5.setMarkerSize(4);
GraphErrors gr_s_fit_km_t_p_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_km_t_p");gr_s_fit_km_t_p_5.setMarkerSize(4);
GraphErrors gr_s_fit_km_f_p_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_km_f_p");gr_s_fit_km_f_p_5.setMarkerSize(4);
GraphErrors gr_s_fit_km_v_p_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_km_v_p");gr_s_fit_km_v_p_5.setMarkerSize(4);
GraphErrors gr_s_fit_km_p_t_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_km_p_t");gr_s_fit_km_p_t_5.setMarkerSize(4);
GraphErrors gr_s_fit_km_t_t_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_km_t_t");gr_s_fit_km_t_t_5.setMarkerSize(4);
GraphErrors gr_s_fit_km_f_t_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_km_f_t");gr_s_fit_km_f_t_5.setMarkerSize(4);
GraphErrors gr_s_fit_km_v_t_5 = (GraphErrors)dir_res5.getObject("/res/gr_s_fit_km_v_t");gr_s_fit_km_v_t_5.setMarkerSize(4);

if(gr_s_fit_el_p_p_1 == null){
	System.out.println("CANNOT FIND OBJECT el vs p 1");    System.exit(0);
}
if(gr_s_fit_el_p_p_2 == null){
	System.out.println("CANNOT FIND OBJECT el vs p 2");    System.exit(0);
}
if(gr_s_fit_el_p_p_5 == null){
	System.out.println("CANNOT FIND OBJECT el vs p 5");    System.exit(0);
}

EmbeddedCanvas can_acc_compare = new EmbeddedCanvas();
can_acc_compare.setSize(1200,1200);
can_acc_compare.divide(2,2);
can_acc_compare.setAxisTitleSize(24);
can_acc_compare.setAxisFontSize(24);
can_acc_compare.setTitleSize(24);
can_acc_compare.cd(0);
can_acc_compare.draw(A2_Phi_1);
can_acc_compare.draw(A2_Phi_2,"same");
can_acc_compare.draw(A2_Phi_3,"same");
can_acc_compare.draw(A2_Phi_4,"same");
can_acc_compare.draw(A2_Phi_5,"same");
can_acc_compare.getPad(0).getAxisX().setRange(-180,180);
can_acc_compare.getPad(0).getAxisY().setRange(0,0.17);
can_acc_compare.cd(1);
can_acc_compare.draw(A2_t_1);
can_acc_compare.draw(A2_t_2,"same");
can_acc_compare.draw(A2_t_3,"same");
can_acc_compare.draw(A2_t_4,"same");
can_acc_compare.draw(A2_t_5,"same");
can_acc_compare.getPad(1).getAxisX().setRange(0,3);
can_acc_compare.getPad(1).getAxisY().setRange(0,0.25);
can_acc_compare.cd(2);
can_acc_compare.draw(A2_Q2_1);
can_acc_compare.draw(A2_Q2_2,"same");
can_acc_compare.draw(A2_Q2_3,"same");
can_acc_compare.draw(A2_Q2_4,"same");
can_acc_compare.draw(A2_Q2_5,"same");
can_acc_compare.getPad(2).getAxisX().setRange(0,12);
can_acc_compare.getPad(2).getAxisY().setRange(0,0.2);
can_acc_compare.cd(3);
can_acc_compare.draw(A2_xB_1);
can_acc_compare.draw(A2_xB_2,"same");
can_acc_compare.draw(A2_xB_3,"same");
can_acc_compare.draw(A2_xB_4,"same");
can_acc_compare.draw(A2_xB_5,"same");
can_acc_compare.getPad(3).getAxisX().setRange(0,0.8);
can_acc_compare.getPad(3).getAxisY().setRange(0,0.25);
can_acc_compare.save("acc_compare.png");

EmbeddedCanvas can_el_res_1D = new EmbeddedCanvas();can_el_res_1D.setSize(2400,1200);can_el_res_1D.divide(4,2);can_el_res_1D.setAxisTitleSize(24);can_el_res_1D.setAxisFontSize(24);can_el_res_1D.setTitleSize(24);
can_el_res_1D.cd(0);can_el_res_1D.draw(gr_s_fit_el_p_p_1);
can_el_res_1D.draw(gr_s_fit_el_p_p_2,"same");
can_el_res_1D.draw(gr_s_fit_el_p_p_3,"same");
can_el_res_1D.draw(gr_s_fit_el_p_p_4,"same");
can_el_res_1D.draw(gr_s_fit_el_p_p_5,"same");
can_el_res_1D.getPad(0).getAxisY().setRange(0, 0.01);
can_el_res_1D.cd(1);can_el_res_1D.draw(gr_s_fit_el_t_p_1);
can_el_res_1D.draw(gr_s_fit_el_t_p_2,"same");
can_el_res_1D.draw(gr_s_fit_el_t_p_3,"same");
can_el_res_1D.draw(gr_s_fit_el_t_p_4,"same");
can_el_res_1D.draw(gr_s_fit_el_t_p_5,"same");
can_el_res_1D.getPad(1).getAxisY().setRange(0, 0.15);
can_el_res_1D.cd(2);can_el_res_1D.draw(gr_s_fit_el_f_p_1);
can_el_res_1D.draw(gr_s_fit_el_f_p_2,"same");
can_el_res_1D.draw(gr_s_fit_el_f_p_3,"same");
can_el_res_1D.draw(gr_s_fit_el_f_p_4,"same");
can_el_res_1D.draw(gr_s_fit_el_f_p_5,"same");
can_el_res_1D.getPad(2).getAxisY().setRange(0, 1); 
can_el_res_1D.cd(3);can_el_res_1D.draw(gr_s_fit_el_v_p_1);
can_el_res_1D.draw(gr_s_fit_el_v_p_2,"same");
can_el_res_1D.draw(gr_s_fit_el_v_p_3,"same");
can_el_res_1D.draw(gr_s_fit_el_v_p_4,"same");
can_el_res_1D.draw(gr_s_fit_el_v_p_5,"same");
can_el_res_1D.getPad(3).getAxisY().setRange(0, 1.5);
can_el_res_1D.cd(4);can_el_res_1D.draw(gr_s_fit_el_p_t_1);
can_el_res_1D.draw(gr_s_fit_el_p_t_2,"same");
can_el_res_1D.draw(gr_s_fit_el_p_t_3,"same");
can_el_res_1D.draw(gr_s_fit_el_p_t_4,"same");
can_el_res_1D.draw(gr_s_fit_el_p_t_5,"same");
can_el_res_1D.getPad(4).getAxisY().setRange(0, 0.01);
can_el_res_1D.cd(5);can_el_res_1D.draw(gr_s_fit_el_t_t_1);
can_el_res_1D.draw(gr_s_fit_el_t_t_2,"same");
can_el_res_1D.draw(gr_s_fit_el_t_t_3,"same");
can_el_res_1D.draw(gr_s_fit_el_t_t_4,"same");
can_el_res_1D.draw(gr_s_fit_el_t_t_5,"same");
can_el_res_1D.getPad(5).getAxisY().setRange(0, 0.15);
can_el_res_1D.cd(6);can_el_res_1D.draw(gr_s_fit_el_f_t_1);
can_el_res_1D.draw(gr_s_fit_el_f_t_2,"same");
can_el_res_1D.draw(gr_s_fit_el_f_t_3,"same");
can_el_res_1D.draw(gr_s_fit_el_f_t_4,"same");
can_el_res_1D.draw(gr_s_fit_el_f_t_5,"same");
can_el_res_1D.getPad(6).getAxisY().setRange(0, 1); 
can_el_res_1D.cd(7);can_el_res_1D.draw(gr_s_fit_el_v_t_1);
can_el_res_1D.draw(gr_s_fit_el_v_t_2,"same");
can_el_res_1D.draw(gr_s_fit_el_v_t_3,"same");
can_el_res_1D.draw(gr_s_fit_el_v_t_4,"same");
can_el_res_1D.draw(gr_s_fit_el_v_t_5,"same");
can_el_res_1D.getPad(7).getAxisY().setRange(0, 1.5);
can_el_res_1D.save("el_res_compare_1D.png");

EmbeddedCanvas can_pr_res_1D = new EmbeddedCanvas();can_pr_res_1D.setSize(2400,1200);can_pr_res_1D.divide(4,2);can_pr_res_1D.setAxisTitleSize(24);can_pr_res_1D.setAxisFontSize(24);can_pr_res_1D.setTitleSize(24);
can_pr_res_1D.cd(0);can_pr_res_1D.draw(gr_s_fit_pr_p_p_1);
can_pr_res_1D.draw(gr_s_fit_pr_p_p_2,"same");
can_pr_res_1D.draw(gr_s_fit_pr_p_p_3,"same");
can_pr_res_1D.draw(gr_s_fit_pr_p_p_4,"same");
can_pr_res_1D.draw(gr_s_fit_pr_p_p_5,"same");
can_pr_res_1D.getPad(0).getAxisY().setRange(0, 0.15);
can_pr_res_1D.cd(1);can_pr_res_1D.draw(gr_s_fit_pr_t_p_1);
can_pr_res_1D.draw(gr_s_fit_pr_t_p_2,"same");
can_pr_res_1D.draw(gr_s_fit_pr_t_p_3,"same");
can_pr_res_1D.draw(gr_s_fit_pr_t_p_4,"same");
can_pr_res_1D.draw(gr_s_fit_pr_t_p_5,"same");
can_pr_res_1D.getPad(1).getAxisY().setRange(0, 3);
can_pr_res_1D.cd(2);can_pr_res_1D.draw(gr_s_fit_pr_f_p_1);
can_pr_res_1D.draw(gr_s_fit_pr_f_p_2,"same");
can_pr_res_1D.draw(gr_s_fit_pr_f_p_3,"same");
can_pr_res_1D.draw(gr_s_fit_pr_f_p_4,"same");
can_pr_res_1D.draw(gr_s_fit_pr_f_p_5,"same");
can_pr_res_1D.getPad(2).getAxisY().setRange(0, 3); 
can_pr_res_1D.cd(3);can_pr_res_1D.draw(gr_s_fit_pr_v_p_1);
can_pr_res_1D.draw(gr_s_fit_pr_v_p_2,"same");
can_pr_res_1D.draw(gr_s_fit_pr_v_p_3,"same");
can_pr_res_1D.draw(gr_s_fit_pr_v_p_4,"same");
can_pr_res_1D.draw(gr_s_fit_pr_v_p_5,"same");
can_pr_res_1D.getPad(3).getAxisY().setRange(0, 2);
can_pr_res_1D.cd(4);can_pr_res_1D.draw(gr_s_fit_pr_p_t_1);
can_pr_res_1D.draw(gr_s_fit_pr_p_t_2,"same");
can_pr_res_1D.draw(gr_s_fit_pr_p_t_3,"same");
can_pr_res_1D.draw(gr_s_fit_pr_p_t_4,"same");
can_pr_res_1D.draw(gr_s_fit_pr_p_t_5,"same");
can_pr_res_1D.getPad(4).getAxisY().setRange(0, 0.15);
can_pr_res_1D.cd(5);can_pr_res_1D.draw(gr_s_fit_pr_t_t_1);
can_pr_res_1D.draw(gr_s_fit_pr_t_t_2,"same");
can_pr_res_1D.draw(gr_s_fit_pr_t_t_3,"same");
can_pr_res_1D.draw(gr_s_fit_pr_t_t_4,"same");
can_pr_res_1D.draw(gr_s_fit_pr_t_t_5,"same");
can_pr_res_1D.getPad(5).getAxisY().setRange(0, 3);
can_pr_res_1D.cd(6);can_pr_res_1D.draw(gr_s_fit_pr_f_t_1);
can_pr_res_1D.draw(gr_s_fit_pr_f_t_2,"same");
can_pr_res_1D.draw(gr_s_fit_pr_f_t_3,"same");
can_pr_res_1D.draw(gr_s_fit_pr_f_t_4,"same");
can_pr_res_1D.draw(gr_s_fit_pr_f_t_5,"same");
can_pr_res_1D.getPad(6).getAxisY().setRange(0, 3); 
can_pr_res_1D.cd(7);can_pr_res_1D.draw(gr_s_fit_pr_v_t_1);
can_pr_res_1D.draw(gr_s_fit_pr_v_t_2,"same");
can_pr_res_1D.draw(gr_s_fit_pr_v_t_3,"same");
can_pr_res_1D.draw(gr_s_fit_pr_v_t_4,"same");
can_pr_res_1D.draw(gr_s_fit_pr_v_t_5,"same");
can_pr_res_1D.getPad(7).getAxisY().setRange(0, 2);
can_pr_res_1D.save("pr_res_compare_1D.png");

EmbeddedCanvas can_kp_res_1D = new EmbeddedCanvas();can_kp_res_1D.setSize(2400,1200);can_kp_res_1D.divide(4,2);can_kp_res_1D.setAxisTitleSize(24);can_kp_res_1D.setAxisFontSize(24);can_kp_res_1D.setTitleSize(24);
can_kp_res_1D.cd(0);can_kp_res_1D.draw(gr_s_fit_kp_p_p_1);
can_kp_res_1D.draw(gr_s_fit_kp_p_p_2,"same");
can_kp_res_1D.draw(gr_s_fit_kp_p_p_3,"same");
can_kp_res_1D.draw(gr_s_fit_kp_p_p_4,"same");
can_kp_res_1D.draw(gr_s_fit_kp_p_p_5,"same");
can_kp_res_1D.getPad(0).getAxisY().setRange(0, 0.025);
can_kp_res_1D.cd(1);can_kp_res_1D.draw(gr_s_fit_kp_t_p_1);
can_kp_res_1D.draw(gr_s_fit_kp_t_p_2,"same");
can_kp_res_1D.draw(gr_s_fit_kp_t_p_3,"same");
can_kp_res_1D.draw(gr_s_fit_kp_t_p_4,"same");
can_kp_res_1D.draw(gr_s_fit_kp_t_p_5,"same");
can_kp_res_1D.getPad(1).getAxisY().setRange(0, 0.75);
can_kp_res_1D.cd(2);can_kp_res_1D.draw(gr_s_fit_kp_f_p_1);
can_kp_res_1D.draw(gr_s_fit_kp_f_p_2,"same");
can_kp_res_1D.draw(gr_s_fit_kp_f_p_3,"same");
can_kp_res_1D.draw(gr_s_fit_kp_f_p_4,"same");
can_kp_res_1D.draw(gr_s_fit_kp_f_p_5,"same");
can_kp_res_1D.getPad(2).getAxisY().setRange(0, 2); 
can_kp_res_1D.cd(3);can_kp_res_1D.draw(gr_s_fit_kp_v_p_1);
can_kp_res_1D.draw(gr_s_fit_kp_v_p_2,"same");
can_kp_res_1D.draw(gr_s_fit_kp_v_p_3,"same");
can_kp_res_1D.draw(gr_s_fit_kp_v_p_4,"same");
can_kp_res_1D.draw(gr_s_fit_kp_v_p_5,"same");
can_kp_res_1D.getPad(3).getAxisY().setRange(0, 5);
can_kp_res_1D.cd(4);can_kp_res_1D.draw(gr_s_fit_kp_p_t_1);
can_kp_res_1D.draw(gr_s_fit_kp_p_t_2,"same");
can_kp_res_1D.draw(gr_s_fit_kp_p_t_3,"same");
can_kp_res_1D.draw(gr_s_fit_kp_p_t_4,"same");
can_kp_res_1D.draw(gr_s_fit_kp_p_t_5,"same");
can_kp_res_1D.getPad(4).getAxisY().setRange(0, 0.025);
can_kp_res_1D.cd(5);can_kp_res_1D.draw(gr_s_fit_kp_t_t_1);
can_kp_res_1D.draw(gr_s_fit_kp_t_t_2,"same");
can_kp_res_1D.draw(gr_s_fit_kp_t_t_3,"same");
can_kp_res_1D.draw(gr_s_fit_kp_t_t_4,"same");
can_kp_res_1D.draw(gr_s_fit_kp_t_t_5,"same");
can_kp_res_1D.getPad(5).getAxisY().setRange(0, 0.75);
can_kp_res_1D.cd(6);can_kp_res_1D.draw(gr_s_fit_kp_f_t_1);
can_kp_res_1D.draw(gr_s_fit_kp_f_t_2,"same");
can_kp_res_1D.draw(gr_s_fit_kp_f_t_3,"same");
can_kp_res_1D.draw(gr_s_fit_kp_f_t_4,"same");
can_kp_res_1D.draw(gr_s_fit_kp_f_t_5,"same");
can_kp_res_1D.getPad(6).getAxisY().setRange(0, 2); 
can_kp_res_1D.cd(7);can_kp_res_1D.draw(gr_s_fit_kp_v_t_1);
can_kp_res_1D.draw(gr_s_fit_kp_v_t_2,"same");
can_kp_res_1D.draw(gr_s_fit_kp_v_t_3,"same");
can_kp_res_1D.draw(gr_s_fit_kp_v_t_4,"same");
can_kp_res_1D.draw(gr_s_fit_kp_v_t_5,"same");
can_kp_res_1D.getPad(7).getAxisY().setRange(0, 5);
can_kp_res_1D.save("kp_res_compare_1D.png");

EmbeddedCanvas can_km_res_1D = new EmbeddedCanvas();can_km_res_1D.setSize(2400,1200);can_km_res_1D.divide(4,2);can_km_res_1D.setAxisTitleSize(24);can_km_res_1D.setAxisFontSize(24);can_km_res_1D.setTitleSize(24);
can_km_res_1D.cd(0);can_km_res_1D.draw(gr_s_fit_km_p_p_1);
can_km_res_1D.draw(gr_s_fit_km_p_p_2,"same");
can_km_res_1D.draw(gr_s_fit_km_p_p_3,"same");
can_km_res_1D.draw(gr_s_fit_km_p_p_4,"same");
can_km_res_1D.draw(gr_s_fit_km_p_p_5,"same");
can_km_res_1D.getPad(0).getAxisY().setRange(0, 0.025);
can_km_res_1D.cd(1);can_km_res_1D.draw(gr_s_fit_km_t_p_1);
can_km_res_1D.draw(gr_s_fit_km_t_p_2,"same");
can_km_res_1D.draw(gr_s_fit_km_t_p_3,"same");
can_km_res_1D.draw(gr_s_fit_km_t_p_4,"same");
can_km_res_1D.draw(gr_s_fit_km_t_p_5,"same");
can_km_res_1D.getPad(1).getAxisY().setRange(0, 0.75);
can_km_res_1D.cd(2);can_km_res_1D.draw(gr_s_fit_km_f_p_1);
can_km_res_1D.draw(gr_s_fit_km_f_p_2,"same");
can_km_res_1D.draw(gr_s_fit_km_f_p_3,"same");
can_km_res_1D.draw(gr_s_fit_km_f_p_4,"same");
can_km_res_1D.draw(gr_s_fit_km_f_p_5,"same");
can_km_res_1D.getPad(2).getAxisY().setRange(0, 2); 
can_km_res_1D.cd(3);can_km_res_1D.draw(gr_s_fit_km_v_p_1);
can_km_res_1D.draw(gr_s_fit_km_v_p_2,"same");
can_km_res_1D.draw(gr_s_fit_km_v_p_3,"same");
can_km_res_1D.draw(gr_s_fit_km_v_p_4,"same");
can_km_res_1D.draw(gr_s_fit_km_v_p_5,"same");
can_km_res_1D.getPad(3).getAxisY().setRange(0, 5);
can_km_res_1D.cd(4);can_km_res_1D.draw(gr_s_fit_km_p_t_1);
can_km_res_1D.draw(gr_s_fit_km_p_t_2,"same");
can_km_res_1D.draw(gr_s_fit_km_p_t_3,"same");
can_km_res_1D.draw(gr_s_fit_km_p_t_4,"same");
can_km_res_1D.draw(gr_s_fit_km_p_t_5,"same");
can_km_res_1D.getPad(4).getAxisY().setRange(0, 0.025);
can_km_res_1D.cd(5);can_km_res_1D.draw(gr_s_fit_km_t_t_1);
can_km_res_1D.draw(gr_s_fit_km_t_t_2,"same");
can_km_res_1D.draw(gr_s_fit_km_t_t_3,"same");
can_km_res_1D.draw(gr_s_fit_km_t_t_4,"same");
can_km_res_1D.draw(gr_s_fit_km_t_t_5,"same");
can_km_res_1D.getPad(5).getAxisY().setRange(0, 0.75);
can_km_res_1D.cd(6);can_km_res_1D.draw(gr_s_fit_km_f_t_1);
can_km_res_1D.draw(gr_s_fit_km_f_t_2,"same");
can_km_res_1D.draw(gr_s_fit_km_f_t_3,"same");
can_km_res_1D.draw(gr_s_fit_km_f_t_4,"same");
can_km_res_1D.draw(gr_s_fit_km_f_t_5,"same");
can_km_res_1D.getPad(6).getAxisY().setRange(0, 2); 
can_km_res_1D.cd(7);can_km_res_1D.draw(gr_s_fit_km_v_t_1);
can_km_res_1D.draw(gr_s_fit_km_v_t_2,"same");
can_km_res_1D.draw(gr_s_fit_km_v_t_3,"same");
can_km_res_1D.draw(gr_s_fit_km_v_t_4,"same");
can_km_res_1D.draw(gr_s_fit_km_v_t_5,"same");
can_km_res_1D.getPad(7).getAxisY().setRange(0, 5);
can_km_res_1D.save("km_res_compare_1D.png");


